[Appearance]
color_scheme_path=/home/sn0w/.config/qt6ct/colors/custom.conf
custom_palette=true
icon_theme=Adwaita
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Adwaita Mono,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Adwaita Mono,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
